name = "HeatEquation"
uuid = "47ed4b48-c1b8-4a04-a284-f84c9c1f202e"
authors = ["Kjartan Thor Wikfeldt <ktwikfeldt@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
